apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: register-app
          image: merict/mongo-crud-pipeline:1.0.0-13
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
