apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-crud
  template:
    metadata:
      labels:
        app: mongo-crud
    spec:
      containers:
        - name: register-crud
          image: merict/mongo-crud-pipeline:test
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3310
