apiVersion: v1
kind: Service
metadata:
  name: mongo-crud-service
  labels:
    app: mongo-app 
spec:
  selector:
    app: mongo-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
