apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-crud-deployment
spec:
  replicas: 1  # Önce 1 replica ile başlayın
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo-crud
  template:
    metadata:
      labels:
        app: mongo-crud
    spec:
      containers:
      - name: register-crud
        image: merict/mongo-crud-pipeline:1.0.0-13
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "development"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/yourdb"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
