apiVersion: v1
kind: Service
metadata:
  name: mongo-crud-service
  labels:
    app: mongo-crud 
spec:
  selector:
    app: mongo-crud

  ports:
    - port: 8080
      targetPort: 3310

  type: LoadBalancer
